from parents import Parents
from children import Children
from grandchildren import Grandchildren

grandma = Parents(name="Dasha", age=65, character='Nordic')
print(grandma.__dict__)
grandma.print_info()
print(grandma.age)
print(grandma.hair)
print("-"*20)
grandpa = Parents(name="Victor", age=70, character='Sanguine')
print(grandpa.__dict__)
print(grandpa.name)
grandpa.print_info()
print("-"*20)
mother = Children(name='Angela', age=38, character='Phlegmatic person')
print(mother.__dict__)
print(mother.eyes)
print(mother.name)
mother.name = "Katya"
print(mother.name)
mother.print_info()
print(type(mother))
print("-"*20)
son = Grandchildren(name='Stepa', age=5, character='Cheerful', eyes='Green', language='English')
son.print_info()
print(son.__dict__)
print(son.hair)
print(son.walk())
print(isinstance(son, Parents))
print(type(son))
print(issubclass(Grandchildren, Parents))
print(son.get_language())
son.set_language('Germany')
print(son.get_language())
print(Grandchildren.hair)
print(son.hair)